GET http://localhost:3001/api/notes

###

DELETE http://localhost:3001/api/notes/2

###

GET https://full-stack-course-simple-web-server.onrender.com/api/notes

###

DELETE https://full-stack-course-simple-web-server.onrender.com/api/notes/4