GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/2

###
GET https://full-stack-course-simple-web-server.onrender.com/api/notes

###
PUT https://full-stack-course-simple-web-server.onrender.com/api/notes/<id of a note to update goes here>
Content-Type: application/json

{
    "content": "Use PUT to update a note.",
    "important": true
}

### Note that id from database is completely different, 24 characters long, e.g. 66e417d8269a6c8bf68a9c1b
DELETE https://full-stack-course-simple-web-server.onrender.com/api/notes/<id of a note to delete goes here>

### Id string must be 24 characters, otherwise goes to catch-branch due to 503 response: 404 "Not found"
GET https://full-stack-course-simple-web-server.onrender.com/api/notes/bad000bad000bad000bad000

### Id string must be 24 characters, otherwise goes to catch-branch due to 503 response: 400 "Malformed id"
GET https://full-stack-course-simple-web-server.onrender.com/api/notes/this-is-bad-id